
function getInfoBasedOnScore(totalScore) {
    
    // Função que retorna informações baseadas na pontuação total.
    if (totalScore >= 20) {
        console.log('Chegou aqui', totalScore)
        // Se a pontuação total for maior ou igual a 20.
        var score_info = "Nível Altíssimo"
        var result_quest = '<p class="result_text">lorem a ur adipisicing elit. Magni magnam, pariatur beatae ipsum omnis totam iusto maxime aut earum quod saepe, unde voluptates. Dolore dolorum, ipsum reprehenderit iusto an<strong>imi ex. Lorem ipsum</strong> dolor sit <br>amet consectetur adipisicing elit. Accusamus illo assumenda nisi modi deserunt. Distinctio magni quibusdam, veniam earum sit eum impedit reiciendis animi, sint tempor</p>'
    } else if (totalScore >= 11) {
        console.log('Chegou aqui', totalScore)
        document.getElementById('printtotalscore').innerHTML = '<h1 class="print-result">Nível <span>Intermediário</span></h1>'
        // Se a pontuação total for entre 11 e 19.
        document.getElementById('printresultquest').innerHTML = '<h2 class="result-title">Procrastinador <span>Relaxado</span></h2><p class="result-text">O procrastinador relaxado é aquele que, ao adiar uma tarefa, opta por fazer algo mais agradável. Ele reconhece que a tarefa evitada é desagradável, mas não se sente culpado por isso e nem se preocupa em lidar rapidamente com as consequências. Esse tipo de procrastinador prefere deixar o tempo passar sem se estressar.</p> <h2 class="result-title">Procrastinador <span>Tenso</span></h2> <p class="result-text">Por outro lado, o procrastinador tenso sabe que deveria realizar a atividade, mas não consegue encontrar motivação suficiente para iniciar. Mesmo procrastinando, ele sente culpa e tensão constantes por não estar se dedicando à tarefa. Essa culpa pode aumentar a ansiedade, criando um ciclo de procrastinação difícil de quebrar.</p><h2 class="result-title-dica">Dicas para <span>ajudar</span> com a <span>procrastinação</span></h2><h2 class="result-title">Dê pequenos primeiros <span>passo</span></h2><p class="result-text-dica"> Iniciar com um pequeno movimento é uma estratégia respaldada pela ciência para superar a procrastinação. A ideia é estabelecer uma meta tão pequena que, “o hedonista em você, que prefere o prazer imediato e adiar as responsabilidades, não conseguirá recusar”.<br> <br>O psicólogo Tim Pychyl, diretor do Centro de Pesquisa sobre Procrastinação da Universidade de Carleton, no Canadá, testou essa abordagem. Seus resultados confirmaram a eficácia: “Uma vez que os alunos começaram, eles avaliaram as tarefas como menos difíceis e estressantes, além de mais agradáveis do que imaginavam”.</p><h2 class="result-title"><span>Estabeleça</span> horários para tudo</h2><p class="result-text-dica">Definir horários é uma estratégia eficaz para combater a procrastinação, pois cria uma programação para o dia. Você saberá exatamente quais tarefas devem ser realizadas em momentos específicos, o que evita a sensação de sobrecarga e desordem. <br> <br> Além disso, estabelecer horários cria um senso de responsabilidade e compromisso. Quando você define um horário para uma tarefa, está criando um compromisso consigo mesmo para realizá-la naquele período determinado. <br> <br> Isso aumenta a motivação e a disciplina, tornando mais provável que você realmente inicie e conclua as tarefas no tempo estipulado.</p>'

        var score_info = '<h1 class="print-result">Nível <span>Intermediário</span></h1>'
        var result_quest = '<h2 class="result-title">Procrastinador <span>Relaxado</span></h2><p class="result-text">O procrastinador relaxado é aquele que, ao adiar uma tarefa, opta por fazer algo mais agradável. Ele reconhece que a tarefa evitada é desagradável, mas não se sente culpado por isso e nem se preocupa em lidar rapidamente com as consequências. Esse tipo de procrastinador prefere deixar o tempo passar sem se estressar.</p> <h2 class="result-title">Procrastinador <span>Tenso</span></h2> <p class="result-text">Por outro lado, o procrastinador tenso sabe que deveria realizar a atividade, mas não consegue encontrar motivação suficiente para iniciar. Mesmo procrastinando, ele sente culpa e tensão constantes por não estar se dedicando à tarefa. Essa culpa pode aumentar a ansiedade, criando um ciclo de procrastinação difícil de quebrar.</p><h2 class="result-title-dica">Dicas para <span>ajudar</span> com a <span>procrastinação</span></h2><h2 class="result-title">Dê pequenos primeiros <span>passo</span></h2><p class="result-text-dica"> Iniciar com um pequeno movimento é uma estratégia respaldada pela ciência para superar a procrastinação. A ideia é estabelecer uma meta tão pequena que, “o hedonista em você, que prefere o prazer imediato e adiar as responsabilidades, não conseguirá recusar”.<br> <br>O psicólogo Tim Pychyl, diretor do Centro de Pesquisa sobre Procrastinação da Universidade de Carleton, no Canadá, testou essa abordagem. Seus resultados confirmaram a eficácia: “Uma vez que os alunos começaram, eles avaliaram as tarefas como menos difíceis e estressantes, além de mais agradáveis do que imaginavam”.</p><h2 class="result-title"><span>Estabeleça</span> horários para tudo</h2><p class="result-text-dica">Definir horários é uma estratégia eficaz para combater a procrastinação, pois cria uma programação para o dia. Você saberá exatamente quais tarefas devem ser realizadas em momentos específicos, o que evita a sensação de sobrecarga e desordem. <br> <br> Além disso, estabelecer horários cria um senso de responsabilidade e compromisso. Quando você define um horário para uma tarefa, está criando um compromisso consigo mesmo para realizá-la naquele período determinado. <br> <br> Isso aumenta a motivação e a disciplina, tornando mais provável que você realmente inicie e conclua as tarefas no tempo estipulado.</p>'
        

        document.getElementById('printresultquest2').innerHTML =  '<h2 class="result-title">Identifique o <span>problema</span>com precisão</h2><p class="result-text-dica">Nem tudo se resume à incapacidade de lidar com responsabilidades. Em alguns casos, não é possível concluir uma tarefa devido à falta de tempo, recursos ou até mesmo de capacitação.<br> <br> Portanto, antes de se culpar, tente entender se houve um motivo realmente justo que impediu a realização de algo. Ao identificar o problema, você pode adotar abordagens específicas para solucioná-lo. <br> <br>Se a sobrecarga de tarefas é o problema, a organização e a priorização adequadas podem ajudar a gerenciar a carga de trabalho. <br> <br> Vale ressaltar que identificar o problema também aumenta a conscientização e a autopercepção. Compreendendo os padrões de comportamento procrastinatórios e as causas subjacentes, você se torna mais consciente de seus próprios hábitos e tendências. Isso permite que você monitore seus padrões de pensamento e comportamento e intervenha quando a procrastinação começa a surgir.</p> <br> <br> <h2 class="result-title">Algumas fontes: </h2> <br> <br> <a class="link" target="_blank" href="https://www.napratica.org.br/dicas-como-parar-de-procrastinar/"><i class="fa-solid fa-paperclip"></i>https://www.napratica.org.br/dicas-como-parar-de-procrastinar/</a> <br>  <br> <a class="link" target="_blank" href="https://fia.com.br/blog/procrastinacao/">  <i class="fa-solid fa-paperclip"></i>https://fia.com.br/blog/procrastinacao/</a> '

        //var result_quest2 = '<h2 class="result-title">Identifique o <span> problema</span>com precisão</h2><p class="result-text-dica">Nem tudo se resume à incapacidade de lidar com responsabilidades. Em alguns casos, não é possível concluir uma tarefa devido à falta de tempo, recursos ou até mesmo de capacitação.<br> <br> Portanto, antes de se culpar, tente entender se houve um motivo realmente justo que impediu a realização de algo. Ao identificar o problema, você pode adotar abordagens específicas para solucioná-lo. <br> <br>Se a sobrecarga de tarefas é o problema, a organização e a priorização adequadas podem ajudar a gerenciar a carga de trabalho. <br> <br> Vale ressaltar que identificar o problema também aumenta a conscientização e a autopercepção. Compreendendo os padrões de comportamento procrastinatórios e as causas subjacentes, você se torna mais consciente de seus próprios hábitos e tendências. Isso permite que você monitore seus padrões de pensamento e comportamento e intervenha quando a procrastinação começa a surgir.</p> <br> <br> <h2 class="result-title">Algumas fontes: </h2> <a class="social-media-item" target="_blank" href="https://www.napratica.org.br/dicas-como-parar-de-procrastinar/"><i class="fa-solid fa-paperclip"></i>https://www.napratica.org.br/dicas-como-parar-de-procrastinar/</a> <br>  <br> <a class="social-media-item" target="_blank" href="https://fia.com.br/blog/procrastinacao/"><i class="fa-solid fa-paperclip"></i>https://fia.com.br/blog/procrastinacao/</a>'

    } else if (totalScore <= 10) {
        console.log('Chegou aqui', totalScore)
        // Se a pontuação total for 10 ou menos.
        var score_info = "Nível Baixo"
        var result_quest = '<p class="result_text">lorem a ur adipisicing elit. Magni magnam, pariatur beatae ipsum omnis totam iusto maxime aut earum quod saepe, unde voluptates. Dolore dolorum, ipsum reprehenderit iusto an<strong>imi ex. Lorem ipsum</strong> dolor sit <br>amet consectetur adipisicing elit. Accusamus illo assumenda nisi modi deserunt. Distinctio magni quibusdam, veniam earum sit eum impedit reiciendis animi, sint tempor</p>'
    }

    

};

// Quando a página carregar, exiba os resultados
window.onload = function () {
    const results = getInfoBasedOnScore(localStorage.getItem('TotalPontos'));
}

function limpaLocalStorage() {
    localStorage.setItem('login','')
}
